/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import entidades.Restaurante;
import datos.Dt_Restaurante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;


/**
 *
 * @author BEATRIZ
 */
public class Frm_Restaurante extends javax.swing.JFrame {
    
    //Declaramos la entidad
    private Restaurante rest = new Restaurante();
    
    //Declarando las clases de datos
    private Dt_Restaurante dtRest = new Dt_Restaurante();
    
    //Declarando la lista de datos
    private ArrayList<Restaurante> listRestaurante = new ArrayList<Restaurante>();
    
    //Declarando el modelo de datos de nuestra tabla
    DefaultTableModel myData = new DefaultTableModel();
    
    public Frm_Restaurante() {
        initComponents();
        llenarTabla_Restaurante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_idRest = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombreRest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_telefonoRest = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_correoRest = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_direccionRest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_paginaWebrest = new javax.swing.JTextField();
        btn_eliminarRest = new javax.swing.JButton();
        btn_nuevoRest = new javax.swing.JButton();
        btn_guardarRest = new javax.swing.JButton();
        btn_editarRest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_restaurante = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txt_buscarRest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Restaurante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Restaurante");

        txt_idRest.setEditable(false);
        txt_idRest.setDisabledTextColor(new java.awt.Color(204, 204, 255));
        txt_idRest.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Direccion");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("RUC");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Pagina web");

        btn_eliminarRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Eliminar.png"))); // NOI18N
        btn_eliminarRest.setText("Eliminar");
        btn_eliminarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarRestActionPerformed(evt);
            }
        });

        btn_nuevoRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Nuevo.png"))); // NOI18N
        btn_nuevoRest.setText("Nuevo");
        btn_nuevoRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoRestActionPerformed(evt);
            }
        });

        btn_guardarRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Guardar.png"))); // NOI18N
        btn_guardarRest.setText("Guardar");
        btn_guardarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarRestActionPerformed(evt);
            }
        });

        btn_editarRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Editar.png"))); // NOI18N
        btn_editarRest.setText("Editar");
        btn_editarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_idRest, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_correoRest, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addComponent(txt_telefonoRest)
                        .addComponent(txt_nombreRest)
                        .addComponent(txt_direccionRest))
                    .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_paginaWebrest, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_eliminarRest, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btn_editarRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_guardarRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nuevoRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_idRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombreRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_telefonoRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_nuevoRest)
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardarRest)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_correoRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_direccionRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editarRest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_paginaWebrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_eliminarRest)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jtbl_restaurante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Restaurante", "Nombre", "Telefono", "Correo", "Direccion", "RUC", "Pagina_web"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_restaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_restauranteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_restaurante);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setText("Buscar");

        txt_buscarRest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarRestKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscarRest, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_buscarRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoRestActionPerformed
        // TODO add your handling code here:
        
        limpiarCampos();
    }//GEN-LAST:event_btn_nuevoRestActionPerformed

    private void btn_guardarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarRestActionPerformed
        // TODO add your handling code here:
        //Validando que todos los campos sean ingresado en el formulario
        if(txt_nombreRest.getText().equals("")||txt_telefonoRest.getText().equals("")||txt_correoRest.getText().equals("")||txt_direccionRest.getText().equals("")||txt_ruc.getText().equals("")||txt_paginaWebrest.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Por favor, todo los campos son requeridos!",
                    "Error",JOptionPane.WARNING_MESSAGE);
            
        }
        else{
            //Construyendo nuestro objeto con los valores del formulario Restaurante
  
            
            rest.setNombre_restaurante(txt_nombreRest.getText());
            rest.setTelefono_restaurante(txt_telefonoRest.getText());
            rest.setCorreo_restaurante(txt_correoRest.getText());
            rest.setDireccion(txt_direccionRest.getText());
            rest.setNumero_ruc(txt_ruc.getText());
            rest.setPagina_web(txt_paginaWebrest.getText());
            
            if(dtRest.existeRestaurante(rest)){
                JOptionPane.showMessageDialog(this, "El registro fue almacenado correctamente",
                        "Mensaje",JOptionPane.INFORMATION_MESSAGE);
                
            }
            else{
                if(dtRest.guardarRestaurante(rest)){
                    JOptionPane.showMessageDialog(this,"El registro se almaceno correctamente",
                     "Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    actualizarTabla();
                    limpiarCampos();
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, 
                            "Revise los datos e intente nuevamente.Si el error persiste contacte al Administrador del Sistema.",
                            "ERROR",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_btn_guardarRestActionPerformed

    private void btn_editarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarRestActionPerformed
        // TODO add your handling code here:
        //Validando que todos los campos sean ingresado
         if(txt_nombreRest.getText().equals("")||txt_telefonoRest.getText().equals("")||txt_correoRest.getText().equals("")||txt_direccionRest.getText().equals("")||txt_ruc.getText().equals("")||txt_paginaWebrest.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Por favor, todo los campos son requeridos!",
                    "Error",JOptionPane.WARNING_MESSAGE);
            
        }
         else{
             //Construyendo nuestros objetos con los valores del formulario
                rest.setRestauranteID(Integer.parseInt(txt_idRest.getText()));
                rest.setNombre_restaurante(txt_nombreRest.getText());
                rest.setTelefono_restaurante(txt_telefonoRest.getText());
                rest.setCorreo_restaurante(txt_correoRest.getText());
                rest.setDireccion(txt_direccionRest.getText());
                rest.setNumero_ruc(txt_ruc.getText());
                rest.setPagina_web(txt_paginaWebrest.getText());
                
                if(dtRest.editarRestaurante(rest)){
                    JOptionPane.showMessageDialog(this,"El registro fue actualizado correctamente!",
                           "Mensaje",JOptionPane.INFORMATION_MESSAGE );
                    actualizarTabla();
                    limpiarCampos();
             
                }
                else{
                    JOptionPane.showMessageDialog(this,
                            "Revise los datos e intente nuevamente",
                            "Error",JOptionPane.ERROR_MESSAGE);
                }
         }
        
    }//GEN-LAST:event_btn_editarRestActionPerformed

    private void btn_eliminarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarRestActionPerformed
        // TODO add your handling code here:
        //Validando que todos los campos sean ingresado por el usuario
        if(txt_nombreRest.getText().equals("")||txt_telefonoRest.getText().equals("")||txt_correoRest.getText().equals("")||txt_direccionRest.getText().equals("")||txt_ruc.getText().equals("")||txt_paginaWebrest.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Por favor, todo los campos son requeridos!",
                    "Error",JOptionPane.WARNING_MESSAGE);
            
        }
        else{
             rest.setRestauranteID(Integer.parseInt(txt_idRest.getText()));
             rest.setNombre_restaurante(txt_nombreRest.getText());
             rest.setTelefono_restaurante(txt_telefonoRest.getText());
             rest.setCorreo_restaurante(txt_correoRest.getText());
             rest.setDireccion(txt_direccionRest.getText());
             rest.setNumero_ruc(txt_ruc.getText());
             rest.setPagina_web(txt_paginaWebrest.getText());
             
             //Validando que el metodo editar devuelva un true
             if(dtRest.deleteRestaurante(rest)){
                 JOptionPane.showMessageDialog(this, "El registro fue eliminado correctamente",
                         "Mensaje",JOptionPane.INFORMATION_MESSAGE);
                         
                         actualizarTabla();
                         limpiarCampos();
             }
             else{
                 JOptionPane.showMessageDialog(this,
                         "Revise los datos e intente nuevamente.Si el error persiste contacte al Administrador del Sistema.",
                         "ERROR",JOptionPane.INFORMATION_MESSAGE);
             }
            
        }
        
    }//GEN-LAST:event_btn_eliminarRestActionPerformed

    private void txt_buscarRestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarRestKeyTyped
        // TODO add your handling code here:
        txt_nombreRest.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (txt_nombreRest.getText()).toUpperCase();
                txt_nombreRest.setText(cadena);
                repaint();
            }
            
        });
    }//GEN-LAST:event_txt_buscarRestKeyTyped

    private void jtbl_restauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_restauranteMouseClicked
        // TODO add your handling code here:
        int fila = this .jtbl_restaurante.getSelectedRow();
        //Asignando los valores a los campos del formulario
        this.txt_idRest.setText(this.jtbl_restaurante.getValueAt(fila,0).toString());
        this.txt_nombreRest.setText(this.jtbl_restaurante.getValueAt(fila,1).toString());
        this.txt_telefonoRest.setText(this.jtbl_restaurante.getValueAt(fila,2).toString());
        this.txt_correoRest.setText(this.jtbl_restaurante.getValueAt(fila,3).toString());
        this.txt_direccionRest.setText(this.jtbl_restaurante.getValueAt( fila,4).toString());
        this.txt_ruc.setText(this.jtbl_restaurante.getValueAt( fila,5).toString());
        this.txt_paginaWebrest.setText(this.jtbl_restaurante.getValueAt( fila,6).toString());
        
        
        
        
    }//GEN-LAST:event_jtbl_restauranteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Restaurante().setVisible(true);
            }
        });
    }
    
    private void llenarTabla_Restaurante(){
        //Llenando la lista
        listRestaurante = dtRest.listarRestaurante();
        
        // Creando el arraylist con las columnas modelos
        ArrayList<Object> listNombreColumnas = new ArrayList<Object>();
        listNombreColumnas.add("ID_Restaurante");
        listNombreColumnas.add("Nombre");
        listNombreColumnas.add("Telefono");
        listNombreColumnas.add("Correo");
        listNombreColumnas.add("Direccion");
        listNombreColumnas.add("RUC");
        listNombreColumnas.add("Pagina_web");
        
        //Recorriendo cada elemento del ArrayList y creando el objeto
        for(Object column : listNombreColumnas){
            //Asignando las columnas al modelo
            myData.addColumn(column);
            
        }
        //Recorriendo cada elementos de la lista y creamo el objeto del modelo
        
        for(Restaurante rests : listRestaurante){
            Object[] datosRest = new Object[] {rests.getRestauranteID(),rests.getNombre_restaurante(),rests.getTelefono_restaurante(),
            rests.getCorreo_restaurante(),rests.getDireccion(),rests.getNumero_ruc(),rests.getNumero_ruc()};
            
            //Asignamos un arreglo de objetos a una fila del modelo
            myData.addRow(datosRest);
            
            //Asignando el modelo o coleccion de datos a la tabla restaurante
            jtbl_restaurante.setModel(myData);
        }
    }
    private void actualizarTabla(){
        myData.setColumnCount(0);
        myData.setRowCount(0);
        this.llenarTabla_Restaurante();
        
    }
    private void limpiarCampos(){
        this.txt_idRest.setText("");
        this.txt_nombreRest.setText("");
        this.txt_telefonoRest.setText("");
        this.txt_correoRest.setText("");
        this.txt_direccionRest.setText("");
        this.txt_ruc.setText("");
        this.txt_paginaWebrest.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editarRest;
    private javax.swing.JButton btn_eliminarRest;
    private javax.swing.JButton btn_guardarRest;
    private javax.swing.JButton btn_nuevoRest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl_restaurante;
    private javax.swing.JTextField txt_buscarRest;
    private javax.swing.JTextField txt_correoRest;
    private javax.swing.JTextField txt_direccionRest;
    private javax.swing.JTextField txt_idRest;
    private javax.swing.JTextField txt_nombreRest;
    private javax.swing.JTextField txt_paginaWebrest;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_telefonoRest;
    // End of variables declaration//GEN-END:variables
}
