/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import datos.Dt_Proveedor;
import entidades.Restaurante;
import datos.Dt_Restaurante;
import java.util.ArrayList;
import entidades.Proveedor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Dennis Caldera
 */
public class FrmProveedor extends javax.swing.JFrame {
    //Atributos 
    //Declaro las entidades
    private Restaurante restaurante = new Restaurante();
    private Proveedor proveedor = new Proveedor();
    //Declaro las clases de datos
    private Dt_Restaurante dtr = new Dt_Restaurante();
    private Dt_Proveedor dtp = new Dt_Proveedor();
    //Declaro lista de datos
    private ArrayList<Restaurante> listRestaurante = new ArrayList<Restaurante>();
    private ArrayList<Proveedor> listProveedor = new ArrayList<Proveedor>();
    //declaramos el modelo de datos de la tabla
    DefaultTableModel myData = new DefaultTableModel();
     //declaramos un filtro de datos para la tabla
    TableRowSorter trsfiltro;
    
    /**
     * Creates new form FrmProveedor
     */
    //Constructor
    public FrmProveedor() {
        initComponents();
        LlenarComboRestaurante();
        llenarTablaProveedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_idProveedor = new javax.swing.JTextField();
        jtf_nombreProveedor = new javax.swing.JTextField();
        jtf_telefonoProveedor = new javax.swing.JTextField();
        jtf_correoProveedor = new javax.swing.JTextField();
        jtf_descripProveedor = new javax.swing.JTextField();
        jtf_pagwebProveedor = new javax.swing.JTextField();
        jcb_Restaurante = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Proveedor = new javax.swing.JTable();
        jb_New = new javax.swing.JButton();
        jb_Save = new javax.swing.JButton();
        jb_Edit = new javax.swing.JButton();
        jb_Delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtf_buscarProv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FrmProveedor");
        setName("FrmProveedor"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ID Proveedor:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Restaurante:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Telefono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Descripcion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pagina Web:");

        jtf_idProveedor.setEditable(false);
        jtf_idProveedor.setFocusable(false);

        jtf_nombreProveedor.setOpaque(true);

        jtf_telefonoProveedor.setOpaque(true);

        jtf_correoProveedor.setOpaque(true);

        jtf_descripProveedor.setOpaque(true);

        jtf_pagwebProveedor.setOpaque(true);
        jtf_pagwebProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_pagwebProveedorActionPerformed(evt);
            }
        });

        jcb_Restaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));

        jtbl_Proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_proveedor", "id_restaurante", "nombre", "telefono", "correo", "descripcion", "pagina_web"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_ProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_Proveedor);

        jb_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Nuevo.png"))); // NOI18N
        jb_New.setText("Nuevo");
        jb_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_NewActionPerformed(evt);
            }
        });

        jb_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Guardar.png"))); // NOI18N
        jb_Save.setText("Guardar");
        jb_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SaveActionPerformed(evt);
            }
        });

        jb_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Editar.png"))); // NOI18N
        jb_Edit.setText("Editar");
        jb_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EditActionPerformed(evt);
            }
        });

        jb_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Eliminar.png"))); // NOI18N
        jb_Delete.setText("Eliminar");
        jb_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_DeleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Buscar:");

        jtf_buscarProv.setOpaque(true);
        jtf_buscarProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_buscarProvKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_idProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_pagwebProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_buscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_correoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_descripProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_New, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtf_idProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcb_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jb_New, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtf_nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtf_telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jb_Save))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_correoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtf_descripProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jb_Edit)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_pagwebProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jb_Delete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_buscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_buscarProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarProvKeyTyped
        // TODO add your handling code here:
            jtf_buscarProv.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtf_buscarProv.getText());
                jtf_buscarProv.setText(cadena);
                repaint();
                filtrarTabla();
            }
        });
        trsfiltro = new TableRowSorter(jtbl_Proveedor.getModel());
        jtbl_Proveedor.setRowSorter(trsfiltro);

    }//GEN-LAST:event_jtf_buscarProvKeyTyped

    private void jb_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_DeleteActionPerformed
        // TODO add your handling code here:

        //validamos que todos los campos sean ingresados por el usuario
        if(jcb_Restaurante.getSelectedIndex()==0 || jtf_nombreProveedor.getText().equals("")|| jtf_telefonoProveedor.getText().equals("") || jtf_correoProveedor.getText().equals("") || jtf_descripProveedor.getText().equals("") || jtf_pagwebProveedor.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!",
                "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            proveedor.setProveedorID(Integer.parseInt(jtf_idProveedor.getText()));
            restaurante = (Restaurante)this.jcb_Restaurante.getItemAt(this.jcb_Restaurante.getSelectedIndex());
            proveedor.setRestauranteID(restaurante.getRestauranteID());
            proveedor.setNombre_proveedor(jtf_nombreProveedor.getText());
            proveedor.setTelefono_proveedor(jtf_telefonoProveedor.getText());
            proveedor.setCorreo_proveedor(jtf_correoProveedor.getText());
            proveedor.setDescripcion(jtf_descripProveedor.getText());
            proveedor.setPagina_web(jtf_pagwebProveedor.getText());

            //validamos que el metodo editar devuelve un true
            if(dtp.deleteProv(proveedor)){
                JOptionPane.showMessageDialog (this, "El registro fue eliminado con éxito!",
                    "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();

            }
            else{
                JOptionPane.showMessageDialog(this,
                    "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jb_DeleteActionPerformed

    private void jb_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EditActionPerformed
        // TODO add your handling code here:

        //validamos que todos los campos sean ingresados por el usuario
        if(jcb_Restaurante.getSelectedIndex()==0 || jtf_nombreProveedor.getText().equals("")|| jtf_telefonoProveedor.getText().equals("") || jtf_correoProveedor.getText().equals("") || jtf_descripProveedor.getText().equals("") || jtf_pagwebProveedor.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!",
                "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            proveedor.setProveedorID(Integer.parseInt(jtf_idProveedor.getText()));
            restaurante = (Restaurante)this.jcb_Restaurante.getItemAt(this.jcb_Restaurante.getSelectedIndex());
            proveedor.setRestauranteID(restaurante.getRestauranteID());
            proveedor.setNombre_proveedor(jtf_nombreProveedor.getText());
            proveedor.setTelefono_proveedor(jtf_telefonoProveedor.getText());
            proveedor.setCorreo_proveedor(jtf_correoProveedor.getText());
            proveedor.setDescripcion(jtf_descripProveedor.getText());
            proveedor.setPagina_web(jtf_pagwebProveedor.getText());

            //validamos que el metodo editar devuelve un true
            if(dtp.editarProv(proveedor)){
                JOptionPane.showMessageDialog (this, "El registro fue actualizado con éxito!",
                    "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();

            }
            else{
                JOptionPane.showMessageDialog(this,
                    "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jb_EditActionPerformed

    private void jb_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SaveActionPerformed
        // TODO add your handling code here:

        //validamos que todos los campos sean ingresados por el usuario
        if(jcb_Restaurante.getSelectedIndex()==0 || jtf_nombreProveedor.getText().equals("")|| jtf_telefonoProveedor.getText().equals("") || jtf_correoProveedor.getText().equals("") || jtf_descripProveedor.getText().equals("") || jtf_pagwebProveedor.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!",
                "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario

            restaurante = (Restaurante)this.jcb_Restaurante.getItemAt(this.jcb_Restaurante.getSelectedIndex());
            proveedor.setRestauranteID(restaurante.getRestauranteID());
            proveedor.setNombre_proveedor(jtf_nombreProveedor.getText());
            proveedor.setTelefono_proveedor(jtf_telefonoProveedor.getText());
            proveedor.setCorreo_proveedor(jtf_correoProveedor.getText());
            proveedor.setDescripcion(jtf_descripProveedor.getText());
            proveedor.setPagina_web(jtf_pagwebProveedor.getText());

            if(dtp.existeProv(proveedor)){
                JOptionPane.showMessageDialog(this,
                    "El proveedor que intenta ingresar ya existe, por favor revise sus datos e intente nuevamente!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            else{
                //validamos que el metodo guardar devuelve un true
                if(dtp.guardarProveedor(proveedor)){
                    JOptionPane.showMessageDialog (this, "El registro fue almacenado con éxito!",
                        "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                    actualizarTabla();
                    limpiarCampos();

                }
                else{
                    JOptionPane.showMessageDialog(this,
                        "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_jb_SaveActionPerformed

    private void jb_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_NewActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jb_NewActionPerformed

    private void jtbl_ProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_ProveedorMouseClicked
        // TODO add your handling code here:

        //obtenemos la fila seleccionada del jtable
        int fila = this.jtbl_Proveedor.getSelectedRow();
        int idRest = 0; //guarda el idRestaurante que se obtiene de la tabla
        int size = 0; //guarda la cantidad de elementos que hay en el jcombobx de Restaurante
        int pos = 1; //variable de control para recorrer las posiciones de los elementos en el jcombobox

        //asignamos los valores a los campos del formulario
        this.jtf_idProveedor.setText(this.jtbl_Proveedor.getValueAt(fila, 0).toString());
        this.jtf_nombreProveedor.setText(this.jtbl_Proveedor.getValueAt(fila, 2).toString());
        this.jtf_telefonoProveedor.setText(this.jtbl_Proveedor.getValueAt(fila, 3).toString());
        this.jtf_correoProveedor.setText(this.jtbl_Proveedor.getValueAt(fila, 4).toString());
        this.jtf_descripProveedor.setText(this.jtbl_Proveedor.getValueAt(fila, 5).toString());
        this.jtf_pagwebProveedor.setText(this.jtbl_Proveedor.getValueAt(fila, 6).toString());

        //obtenemos el idLocations del jtable
        idRest = Integer.parseInt(this.jtbl_Proveedor.getValueAt(fila, 1).toString());
        System.out.println("idRest: "+idRest);

        size = this.jcb_Restaurante.getItemCount(); //obtenemos la cantidad de elementos contenidos en el jcombobox
        System.out.println("size: "+size);
        do{

            restaurante = (Restaurante)this.jcb_Restaurante.getItemAt(pos);
            if(restaurante.getRestauranteID()==idRest){
                //selecciono el objeto del jcombobox
                this.jcb_Restaurante.setSelectedIndex(pos);
                System.out.println("pos: "+pos);
                break;
            }
            pos++;

        }
        while(pos<=size);

    }//GEN-LAST:event_jtbl_ProveedorMouseClicked

    private void jtf_pagwebProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_pagwebProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_pagwebProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProveedor().setVisible(true);
            }
        });
    }

    //metodos
    private void LlenarComboRestaurante(){
        //llenamos la lista
        listRestaurante = dtr.listarRestaurante();
        
        for(Restaurante r: listRestaurante){
        //llenar combobox con los objetos de la lista
        this.jcb_Restaurante.addItem(r);
    }
    }
    
    private void llenarTablaProveedor(){
        //llenamos la lista
        listProveedor = dtp.listarProveedor();
        
        //creamos un arraylist con las columnas del modelo
        ArrayList<Object> listNombreColumnas = new ArrayList<Object>();
        listNombreColumnas.add("id_proveedor");
        listNombreColumnas.add("id_restaurante");
        listNombreColumnas.add("nombre");
        listNombreColumnas.add("telefono");
        listNombreColumnas.add("correo");
        listNombreColumnas.add("descripcion");
        listNombreColumnas.add("pagina_web");
        //recorremos cada elementos del arraylist y creamos un objeto
         for(Object column : listNombreColumnas){
            //asignamos las columnas al modelo
            myData.addColumn(column);
        }
        //recorremos cada elemento de la lista y creamos el objeto
         for(Proveedor prov: listProveedor){
            Object[] datosProv = new Object[]{prov.getProveedorID(), prov.getRestauranteID(), prov.getNombre_proveedor(), prov.getTelefono_proveedor(), prov.getCorreo_proveedor(), prov.getDescripcion(), prov.getPagina_web()};
            //asignamos un arreglo de objetos a una fila del modelo
            myData.addRow(datosProv);
        }
        //Asignamos el modelo y/o coleccion de datos a la tabla
        jtbl_Proveedor.setModel(myData);
    }
      
    private void actualizarTabla(){
        myData.setColumnCount(0);
        myData.setRowCount(0);
        this.llenarTablaProveedor();
    }
    
    private void filtrarTabla(){
       trsfiltro.setRowFilter(RowFilter.regexFilter(jtf_buscarProv.getText(),1, 2));
    }
    
    private void limpiarCampos()
    {
        this.jtf_nombreProveedor.setText("");
        this.jtf_idProveedor.setText("");
        this.jtf_telefonoProveedor.setText("");
        this.jtf_correoProveedor.setText("");
        this.jtf_descripProveedor.setText("");
        this.jtf_pagwebProveedor.setText("");
        this.jcb_Restaurante.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Delete;
    private javax.swing.JButton jb_Edit;
    private javax.swing.JButton jb_New;
    private javax.swing.JButton jb_Save;
    private javax.swing.JComboBox<Object> jcb_Restaurante;
    private javax.swing.JTable jtbl_Proveedor;
    private javax.swing.JTextField jtf_buscarProv;
    private javax.swing.JTextField jtf_correoProveedor;
    private javax.swing.JTextField jtf_descripProveedor;
    private javax.swing.JTextField jtf_idProveedor;
    private javax.swing.JTextField jtf_nombreProveedor;
    private javax.swing.JTextField jtf_pagwebProveedor;
    private javax.swing.JTextField jtf_telefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
