/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import entidades.Rol;
import entidades.Usuario;
import datos.Dt_Rol;
import datos.Dt_Usuario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Mariano Lacayo
 */
public class FrmUsuario extends javax.swing.JFrame {
    
    private Rol rol = new Rol();
    private Usuario user = new Usuario();
    //declaro las clases de datos
    private Dt_Rol dtr = new Dt_Rol();
    private Dt_Usuario dtuser = new Dt_Usuario();
    //declaro las listas de datos
    private ArrayList<Rol> listRol = new ArrayList<Rol>();
    private ArrayList<Usuario> listUser = new ArrayList<Usuario>();
    //declaramos el modelo de datos de la tabla 
    DefaultTableModel myData = new DefaultTableModel();
    //declaramos un filtro de datos para la tabla
    TableRowSorter trsfiltro;

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        llenarComboRol();
        llenarTablaUser();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassUser = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtPassConfirm = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuscadorUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jb_Edit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Rol ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 30, -1));

        txtUserID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserID.setEnabled(false);
        txtUserID.setOpaque(true);
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 30, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("UsuarioID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtUserName.setOpaque(true);
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre_usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtPassUser.setOpaque(true);
        jPanel1.add(txtPassUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Clave");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtPassConfirm.setOpaque(true);
        jPanel1.add(txtPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Confirmar clave");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        cmbRol.setOpaque(true);
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        txtEstado.setEditable(false);
        txtEstado.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtEstado.setOpaque(true);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 30, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Buscar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtBuscadorUser.setOpaque(true);
        txtBuscadorUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorUserActionPerformed(evt);
            }
        });
        txtBuscadorUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorUserKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscadorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 570, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 385, 290));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Nuevo.png"))); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Guardar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        jb_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Editar.png"))); // NOI18N
        jb_Edit.setText("Editar");
        jb_Edit.setOpaque(true);
        jb_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EditActionPerformed(evt);
            }
        });
        jPanel2.add(jb_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/multimedia/m_Eliminar.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 230, 270));

        jButton3.setText("Roles");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 80, -1));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UsuarioID", "RolID", "Nombre_usuario", "Estado"
            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtBuscadorUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorUserActionPerformed

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // TODO add your handling code here:
         txtUserName.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (txtUserName.getText());
                txtUserName.setText(cadena);
                repaint();
            }
        });
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtBuscadorUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorUserKeyTyped
        // TODO add your handling code here:
        txtBuscadorUser.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (txtBuscadorUser.getText());
                txtBuscadorUser.setText(cadena);
                repaint();
                filtrarTabla();
            }
        });
        trsfiltro = new TableRowSorter(tblUsers.getModel());
        tblUsers.setRowSorter(trsfiltro);
    }//GEN-LAST:event_txtBuscadorUserKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(txtUserName.getText().equals("") || cmbRol.getSelectedIndex()==0 || txtPassUser.getText().equals("") || txtPassConfirm.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            if (txtPassUser.getText().equals(txtPassConfirm.getText())){
            //construimos nuestro objeto con los valores del formulario
            user.setNombre_usuario(txtUserName.getText());
            rol = (Rol)this.cmbRol.getItemAt(this.cmbRol.getSelectedIndex());
            user.setRolID(rol.getRolID());
            user.setClave(txtPassUser.getText());
            user.setEstado(1);
            

                //validamos que el metodo guardar devuelve un true
                if(dtuser.guardarUser(user)){
                    JOptionPane.showMessageDialog (this, "El registro fue almacenado con éxito!", 
                      "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                    actualizarTabla();
                    limpiarCampos();
                    
                }
                else{
                   JOptionPane.showMessageDialog(this, 
                      "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                      "ERROR", JOptionPane.ERROR_MESSAGE); 
                }
            } else{JOptionPane.showMessageDialog(this, "Las claves deben ser iguales!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jb_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EditActionPerformed
        // TODO add your handling code here:
        //validamos que todos los campos sean ingresados por el usuario      
        if(txtUserName.getText().equals("") || cmbRol.getSelectedIndex()==0 || txtPassUser.getText().equals("") || txtPassConfirm.getText().equals("") || txtEstado.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            if (txtPassUser.getText().equals(txtPassConfirm.getText())){
            //construimos nuestro objeto con los valores del formulario
            user.setUsuarioID(Integer.parseInt(txtUserID.getText()));
            user.setNombre_usuario(txtUserName.getText());
            rol = (Rol)this.cmbRol.getSelectedItem();
            user.setRolID(rol.getRolID());
            user.setClave(txtPassUser.getText());
            user.setEstado(Integer. parseInt(txtEstado.getText()));
            
            }else{JOptionPane.showMessageDialog(this, "Las claves deben ser iguales!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            //validamos que el metodo actualizar devuelve un true
            if(dtuser.editarUsuario(user)){
                JOptionPane.showMessageDialog (this, "El registro fue actualizado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
               JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }   
    }//GEN-LAST:event_jb_EditActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(txtUserName.getText().equals("") || cmbRol.getSelectedIndex()==0 || txtPassUser.getText().equals("") || txtPassConfirm.getText().equals("") || txtEstado.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            user.setUsuarioID(Integer.parseInt(txtUserID.getText()));
            user.setNombre_usuario(txtUserName.getText());
            rol = (Rol)this.cmbRol.getSelectedItem();
            user.setRolID(rol.getRolID());
            user.setClave(txtPassUser.getText());
            user.setEstado(Integer.parseInt(txtEstado.getText()));
            
            //validamos que el metodo delete devuelve un true
            if(dtuser.deleteUser(user.getUsuarioID())){
                JOptionPane.showMessageDialog (this, "El registro fue eliminado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
               JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        // TODO add your handling code here:
        int fila = this.tblUsers.getSelectedRow();
        int idRol = 0; 
        int size = 0; 
        int pos = 0; 
        
        
        this.txtUserID.setText(this.tblUsers.getValueAt(fila, 0).toString());
        this.txtUserName.setText(this.tblUsers.getValueAt(fila, 2).toString());
        this.txtEstado.setText(this.tblUsers.getValueAt(fila, 3).toString());
        
        idRol = Integer.parseInt(this.tblUsers.getValueAt(fila, 1).toString());
        System.out.println("idRol: "+idRol);
  
        size = this.cmbRol.getItemCount(); //obtenemos la cantidad de elementos contenidos en el jcombobox
        System.out.println("size: "+size);
        do{
            pos++;
            rol = (Rol)this.cmbRol.getItemAt(pos);
            if(rol.getRolID()==idRol){
                //selecciono el objeto del jcombobox
                this.cmbRol.setSelectedIndex(pos);
                System.out.println("pos: "+pos);
                break;
            }
            
        }
        while(pos<=size);
    }//GEN-LAST:event_tblUsersMouseClicked

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(cmbRol.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
         rol = (Rol)this.cmbRol.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Nombre:  "+rol.getRol_nombre()+" ID:  "+rol.getRolID());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });    
    }
    //metodos papu
    private void llenarComboRol(){
        //llenamos la lista
        listRol = dtr.listarRol();
        
        for(Rol rl: listRol){
            //llenar el combobox con los objetos de la lista
            
            this.cmbRol.addItem(rl);
        }
    }
    
    
    
    private void actualizarTabla(){
        myData.setColumnCount(0);
        myData.setRowCount(0);
        this.llenarTablaUser();
    }
    
    private void llenarTablaUser()
    {
         //llenamos la lista
        listUser = dtuser.listarUser();
        
        //creamos un arraylist con las columnas del modelo
        ArrayList<Object> listNombreColumnas = new ArrayList<Object>();
        listNombreColumnas.add("UsuarioID");
        listNombreColumnas.add("RolID");
        listNombreColumnas.add("Nombre_usuario");
        listNombreColumnas.add("Estado");
        
        //recorremos cada elemento del arraylist y creamos un objeto
        for(Object column : listNombreColumnas){
            //asignamos las columnas al modelo
            myData.addColumn(column);
        }
        
       //recorremos cada elemento de la lista y creamos el objeto
        for(Usuario us: listUser){
            Object[] datosuser = new Object[]{us.getUsuarioID(), us.getRolID(), us.getNombre_usuario(), us.getEstado()};
            //asignamos un arreglo de objetos a una fila del modelo
            myData.addRow(datosuser);
        }
        //Asignamos el modelo y/o coleccion de datos a la tabla
        tblUsers.setModel(myData);
    }
    
    private void filtrarTabla(){
       trsfiltro.setRowFilter(RowFilter.regexFilter(txtBuscadorUser.getText(),1, 2));
    }
    
     private void limpiarCampos()
    {
        this.txtUserID.setText("");
        this.txtUserName.setText("");
        this.txtPassUser.setText("");
        this.txtPassUser.setText("");
        this.txtPassConfirm.setText("");
        this.txtEstado.setText("");
        this.cmbRol.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cmbRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Edit;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtBuscadorUser;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JPasswordField txtPassConfirm;
    private javax.swing.JPasswordField txtPassUser;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
